### ISSUE TITLE
Can you share the implementation codes for AutoAttack? (FSGM)

### ISSUE THREAD

**Issue by wjun0830** [iCGY96/APR#2]
I read your paper very impressive using Fourier transform.
I wish I could have the implementations to run the AutoAttack experiments.
Can you share your code for FSGM training/eval?

**Comment by gary23ai** [comment]
Thank you for your attention to our work.

For the FSGM training, we refer to the official training code ([repo](https://github.com/locuslab/fast_adversarial)) and add our method of APR in the training. The AutoAttack experiments also refer to the official code ([repo](https://github.com/fra31/auto-attack)).

We will provide some trained models in the near future.
