### ISSUE TITLE
randomness in apr-p and apr-s

### ISSUE THREAD

**Issue by kiranchari** [iCGY96/APR#3]
Hi

I see that in both APR-P and APR-S there is some randomness in the augmentations. For APR-P, the data is mixed only 40% of the time https://github.com/iCGY96/APR/blob/ca61e352c5ea6e8078776f605c03752abcd29493/core/train.py#L16 

and in APR-S, the data is augmented 50% of the time https://github.com/iCGY96/APR/blob/ca61e352c5ea6e8078776f605c03752abcd29493/datasets/APR.py#L25 

with additional randomness in the choice of image whose phase is returned https://github.com/iCGY96/APR/blob/ca61e352c5ea6e8078776f605c03752abcd29493/datasets/APR.py#L46

Were these steps used to obtain the results in your paper, as I do not find this randomness mentioned in the paper?

Also, could you briefly describe how APR-SP was implemented - did you first apply APR-S and then apply APR-P?

Thank you,
KC

**Comment by gary23ai** [comment]
Thanks for your attention!

Were these steps used to obtain the results in your paper, as I do not find this randomness mentioned in the paper?
- Yes, we use a random probability. Too many data augmentations would have a certain negative impact on the clean images. These probabilities could be changed according to different applications.

Also, could you briefly describe how APR-SP was implemented - did you first apply APR-S and then apply APR-P?
- Your understanding is correct. Through the above probability setting, too much overlap between APR-S and APR-P is prevented.

**Comment by kiranchari** [comment]
Thanks for your reply @iCGY96.

I see that the APR-S and APR-P minibatches are concatenated - I suppose this is the APR-SP implementation by default in this code? https://github.com/iCGY96/APR/blob/ca61e352c5ea6e8078776f605c03752abcd29493/core/train.py#L54

**Comment by gary23ai** [comment]
'inputs' and 'inputs_mix' may both include images processed by APR-S. This code is mainly for APR-P and to ensure that the minibatches contain a certain number of clean images.

**Comment by kiranchari** [comment]
Thanks. Are you exploring applications in GANs?https://github.com/iCGY96/APR/blob/b8f1e18258b6557250ee780bfefa8f06f56e4d89/utils/utils.py#L84

**Comment by gary23ai** [comment]
This is the redundancy of some reference codes, and I will delete them immediately. Thanks!
