### ISSUE TITLE
Can you share your ResNet-50 model checkpoint?

### ISSUE THREAD

**Issue by double-fire-0** [iCGY96/APR#4]
I want to use your pretrain model to do other experiments.
Can you share your ResNet-50 model checkpoint?

Thanks

**Comment by gary23ai** [comment]
Hello, thanks for your interest. The README has been updated with a link to the  ResNet-50. It can be found here

**Comment by double-fire-0** [comment]
Hi, I can see the link on README, but it seems that you didn't open the permission of this file.
Can you fix it?

Thanks

**Comment by gary23ai** [comment]
Hi, these files can be downloaded by different accounts. Could you tell me the details of the permission problem you encountered?

**Comment by double-fire-0** [comment]
I can download it now! It may be caused by my network problem.
