### ISSUE TITLE
Question about the section 5.3 in your paper.

### ISSUE THREAD

**Issue by CoderHHX** [iCGY96/APR#6]
Hi @iCGY96! Thanks for your insightful work! I found it is hard to understand in Section 5.3: Labeled by Amplitude or Phase? In this section, the authors investigated the use of labels amplitude and phase separately. "The model is trained for the sample x combined by the phase spectrum Pxi and the amplitude spectrum Axj by optimizing Eq(7)". How to understand x combined by the phase spectrum P and the amplitude spectrum A. Is it means that you first decouple the x into A and P, then input the A and P to the networks with two FC
layers, or input [X, P] and [X, A] into the networks?

**Comment by gary23ai** [comment]
Thanks for your attention!

For two images xi and xj, sample x is combined by the phase spectrum P_xi and the amplitude spectrum A_xj. Then, the model is trained with (x, yi, yj) by Eq(7).

I hope this will help you!

**Comment by CoderHHX** [comment]
Thanks so much for your reply! I get your meaning. One more question, have you tried to train a model only with Amplitude input or Phase input?

**Comment by gary23ai** [comment]
We didn't try that, but it's a direction worth exploring in the future.
