### ISSUE TITLE
Hi, I meet the 404 error when download the pretrained models 

### ISSUE THREAD

**Issue by vtddggg** [iCGY96/APR#7]
the shared link of [APR-SP](https://drive.google.com/drive/folders/1HL2y3a4BwwoXyF-29GfFW-XoP8DZrCVy?usp=sharing) model seems broken, and yields a 404 error
![image](https://user-images.githubusercontent.com/27721248/190291191-e2e5a507-7005-4268-89e0-c206a0e66a2e.png)

**Comment by vtddggg** [comment]
same problem with the [DeepAugMent+(ARP-SP)](https://drive.google.com/drive/folders/1HL2y3a4BwwoXyF-29GfFW-XoP8DZrCVy?usp=sharing) model

**Comment by gary23ai** [comment]
There are some problems with my Google account. I will fix them as soon as possible

**Comment by vtddggg** [comment]
thanks for your help!
We will release a robust training tools/benchmark in a few days.  Your pretrained model can improve the recognition of our benchmark. Also we will inform you once the tool is open-sourced.

**Comment by gary23ai** [comment]
The download link has been fixed!
Thank you for your attention to our paper and we look forward to your robust training tools/benchmark release.

**Comment by vtddggg** [comment]
We have released EasyRobust v0.2.0 today, which includes APR in Non-Adversarial Robust Benchmark. 

You can click [here](https://github.com/alibaba/easyrobust#non-adversarial-robust-benchmark-sorted-by-imagenet-c) to visit it. Contact us if there is any problem. Thanks !!
